
/*
  Auto-generated Arduino Stress Indicator Simulation
  LED ON  = Stress detected (1)
  LED OFF = Baseline (0)
  Predictions generated by ML model from Python
*/

const int ledPin = 13; // Built-in LED

// Predictions array
int predictions[] = {0, 1, 1, 1};
int numPredictions = 4;

void setup() {
  pinMode(ledPin, OUTPUT);
  Serial.begin(9600);
  Serial.println("Stress Detection Simulation Started");
}

void loop() {
  for (int i = 0; i < numPredictions; i++) {
    if (predictions[i] == 1) {
      digitalWrite(ledPin, HIGH); // Stress detected → LED ON
      Serial.println("Stress detected! LED ON");
    } else {
      digitalWrite(ledPin, LOW); // Baseline → LED OFF
      Serial.println("Baseline. LED OFF");
    }
    delay(1000); // 1 second per prediction
  }
  // Repeat the sequence
}
